version: '3.2'

networks:
  default:
    driver: bridge

services:

    memcached:
      image: memcached:alpine
      container_name: cms-memcached
      networks:
        - default

    mailhog:
      image: mailhog/mailhog:latest
      container_name: cms-mailhog
      ports:
        - "8082:8025"
      networks:
        - default

    redis:
      image: redis:alpine
      container_name: cms-redis
      networks:
        - default

    mysql:
      image: mysql
      container_name: cms-mysql
      command: --default-authentication-plugin=mysql_native_password
      networks:
        - default
      volumes:
        - ./docker/mysql/data/:/var/lib/mysql
        - ./log/mysql:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=88888888
        - MYSQL_DATABASE=dvaduhaniya
        - MYSQL_USER=msarapii
        - MYSQL_PASSWORD=88888888
      ports:
        - "8083:3306"
      restart: always

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_USER: msarapii
        PMA_PASSWORD: 88888888
      ports:
        - "8088:80"
      restart: always
      depends_on:
        - mysql
      networks:
        - default

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: cms-elasticsearch
      networks:
        - default

    webserver-front:
      image: nginx:alpine
      container_name: cms-webserver-front
      networks:
        - default
      working_dir: /app
      volumes:
          - ./cms:/app
          # Re-use local composer cache via host-volume
          - ~/.composer-docker/cache:/root/.composer/cache:delegated
          - ./docker/nginx/nginx-front.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"


    webserver-back:
      image: nginx:alpine
      container_name: cms-webserver-back
      networks:
        - default
      working_dir: /app
      volumes:
        - ./cms:/app
        # Re-use local composer cache via host-volume
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./docker/nginx/nginx-back.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: cms-php-fpm
      networks:
        - default
      working_dir: /app
      volumes:
        - ./cms:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

# docker exec -i -t 6ee6223a3ce3 bash     //подключиться к запущенному контейнеру
